server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jcafure/jokenpo-configs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/